/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import DB.CRUD;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author caballeroda_sd2081
 */
public class UserList extends javax.swing.JFrame {


//    DefaultTableModel tm;
     CRUD c = new CRUD();
    DefaultTableModel tm;
    private static String adminPass = "admin";
    boolean admin = false;
    private static String user;
    private String data = "";
    private static Object username = "";
    JFrame frame = new JFrame();
    Dimension dimension;
    boolean edit = true;


    public UserList() {
        initComponents();
        showlist();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

//    public ArrayList<User> userList(){
//         ArrayList<User> userList = new ArrayList<User>();
//         
//         try {
//           // create a mysql database connection
//           String myDriver = "com.mysql.jdbc.Driver";
//           String myUrl = "jdbc:mysql://localhost/dainedb";
////           Class.forName(myDriver);
//           Connection conn = DriverManager.getConnection(myUrl, "root", "");
//
//           String query = "SELECT * FROM tblUserList";
//           
//           Statement st = conn.createStatement();
//            java.sql.ResultSet rs = st.executeQuery(query);
//            
//            User user;
//            while(rs.next()){
//                user = new User(rs.getInt("userId"),rs.getString("First_Name"), rs.getString("Middle_Name"), rs.getString("Last_Name"), rs.getString("EMail"), rs.getString("UserName"));
//                userList.add(user);
//            }
//
//           // note that i'm leaving "date_created" out of this insert statement
////           st.executeUpdate(sqlString);
//
//           conn.close();
//        
//       } catch (SQLException e) {
//           System.err.println("Got an exception!");
//           System.err.println(e.getMessage());
//           return null;
//       }
//        return userList;
//         
//     }
//    
//    public void show_list(){
//        ArrayList <User> list = userList();
//        DefaultTableModel model = (DefaultTableModel) jTable_User_List.getModel();
//        Object [] row = new Object [6];
//        for(int i = 0; i<list.size(); i++){
//            row [0] = list.get(i).getUserId();
//            row [1] = list.get(i).getFirst_Name();
//            row [2] = list.get(i).getMiddle_Name();
//            row [3] = list.get(i).getLast_Name();
//            row [4] = list.get(i).getEMail();
//            row [5] = list.get(i).getUserName();
//            model.addRow(row);
//            
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        LogOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(153, 204, 255));
        jTable1.setForeground(new java.awt.Color(102, 102, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "userId", "First Name", "Middle Name", "Last Name", "Email", "Username"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTable1ComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                jTable1ComponentRemoved(evt);
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        LogOut.setBackground(new java.awt.Color(0, 0, 0));
        LogOut.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        LogOut.setForeground(new java.awt.Color(255, 51, 255));
        LogOut.setText("LogOut");
        LogOut.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));
        LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutMouseClicked(evt);
            }
        });
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 255));
        jLabel1.setText("WELCOME");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogOut)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
//        Details d = new Details();
//        d = setVisible(true);
//        this.setVisible(false);

//        int row = jTable1.getSelectedRow();
//        int column = jTable1.getColumnCount();
//        String data = "";
//        for (int i = 0; i< column; i++){
//            data += jTable1.getValueAt(row, i)+"\n";
//        }
//        JOptionPane.showMessageDialog(null, data);
//
        int row = jTable1.getSelectedRow();
        int column = jTable1.getSelectedColumn();
//        String data = "";
        username = jTable1.getValueAt(row, 4);
        if (!user.equals(username)){
        for (int i = 0; i <= column; i++) {
            data += jTable1.getValueAt(row, i) + "\n";
        }
        JOptionPane.showMessageDialog(null, data);
        }
        if (!jTable1.getSelectionModel().isSelectionEmpty()) {
            if (admin) {

                String accountQuery = "DELETE FROM users WHERE Email=" + "\"" + username + "\"" + ";";
                delete(accountQuery);
            }
            if (admin == false) {

                String accountQue = "DELETE FROM users WHERE Email=" + "\"" + user + "\"" + ";";
                String accountQuery = "UPDATE users SET First_Name = ? ,"
                        + "Middle_Name = ? ,"
                        + "Last_Name = ? ,"
                        + "EMail = ?,"
                        + "UserName = ?,"
                        + "Password = ?"
                        + "WHERE UserName =" + "\"" + username + "\"" + ";";

                JButton editbtn = new JButton("EDIT");
                editbtn.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        if (username.equals(user)) {
                            for (int i = 0; i <= column; i++) {
                                data += jTable1.getValueAt(row, i) + "\n";
                            }
                            edit(accountQuery);
                        }
                        data = "";
                    }

                    private void edit(String accountQuery) {
                        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                    }

   
                });
                JButton deletebtn = new JButton("DELETE");
                deletebtn.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        if (username.equals(user)) {
                            for (int i = 0; i <= column; i++) {
                                data += jTable1.getValueAt(row, i) + "\n";
                            }
                            delete(accountQue);
                        }
                        data = "";
                    }
                });

                frame.add(editbtn, BorderLayout.WEST);
                frame.add(deletebtn, BorderLayout.EAST);
                frame.pack();
                frame.setLocation(dimension.width / 2 - this.getSize().width / 5, dimension.height / 2 - this.getSize().height / 5);
                if (username.equals(user)) {
                    frame.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

     public void showlist() {
       
       String Query = "SELECT * FROM tblUserList";
       try{
           tm = (DefaultTableModel) jTable1.getModel();
           Connection conn = c.connectToDB();
           ResultSet rs = c.getData(Query);
           while(rs.next()) {
               tm.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7)});
           }
           conn.close();
       }catch(Exception e) {
           System.out.println(e.getMessage());
       }
       
       
   }
     
      public void setAdmin(boolean administrator) {
        this.admin = administrator;
    }

    public void setUser(String userN) {
        this.user = userN;
    }
    
    private void LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseClicked
        LogIn li = new LogIn();
        li.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LogOutMouseClicked

    private void jTable1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTable1ComponentAdded
         
         
        
        //int i = 0;
//            if (rs.next()) {
//                uname = rs.getString("uname");
//                email = rs.getString("umail");
//                pass = rs.getString("upass");
//                cou = rs.getString("ucountry");
//                model.addRow(new Object[]{uname, email, pass, cou});
//                i++;
            
    }//GEN-LAST:event_jTable1ComponentAdded

    private void jTable1ComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTable1ComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1ComponentRemoved

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserList.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserList.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserList.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserList.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void delete(String accountQuery) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
